fruits-image-path: 'C:\Users\Patrick\Documents\TU\2019S\ML\ML_Exercise3\ML_Exercise3\data\FIDS30'
cars-image-path: 'C:\Users\Patrick\Documents\TU\2019S\ML\ML_Exercise3\ML_Exercise3\data\CarData'
plot-path: 'C:\Users\Patrick\Documents\TU\2019S\ML\ML_Exercise3\ML_Exercise3'
tensorboard-log-path: 'C:\Users\Patrick\Documents\TU\2019S\ML\ML_Exercise3\ML_Exercise3\logs2'
optimizer: sgd
image-size-x: 100
image-size-y: 40
batch-size: 32
epochs: 100
steps-per-epoch: 6000