fruits-image-path: 'C:\Users\Patrick\Documents\TU\2019S\ML\ML_Exercise3\ML_Exercise3\data\FIDS30'
cars-image-path: 'C:\Users\Patrick\Documents\TU\2019S\ML\ML_Exercise3\ML_Exercise3\data\CarData'
plot-path: 'C:\Users\Patrick\Documents\TU\2019S\ML\ML_Exercise3\ML_Exercise3'
tensorboard-log-path: 'C:\Users\Patrick\Documents\TU\2019S\ML\ML_Exercise3\ML_Exercise3\logs3'
fruits-model: lenet5 #example
transfer-model: vgg16 #vgg16, resnet50, mobilenet
optimizer: sgd
cars-image-size-x: 100
cars-image-size-y: 40
fruits-image-size-x: 64
fruits-image-size-y: 64
batch-size: 32
epochs: 50
steps-per-epoch: 2000